version: '3'
services:
  client:
    image: 'agung96tm/multi-client'
    mem_limit: 128m
    hostname: client

  server:
    image: 'agung96tm/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  worker:
    image: "agung96tm/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: "agung96tm/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"