name: Deploy Dev

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches:
      - feature/*
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Build & Test'
        run: |
          docker build -t agung96tm/frontend -f Dockerfile.dev .
          docker run -e CI=true agung96tm/frontend npm run test -- --coverage
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        #  if: github.ref == 'refs/heads/main'
        if: github.ref == 'refs/heads/feature/section-7'
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          region: ap-southeast-1
          use_existing_version_if_available: true
