name: Deploy Dev

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Build'
        run: |
          docker build -t agung96tm/frontend -f Dockerfile.dev .
      - name: 'Test'
        run: |
          docker run -e CI=true agung96tm/frontend npm run test -- --coverage